name: friend_private
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.20+84


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  
  
  archive: ^3.6.1
  auto_size_text: 3.0.0
  awesome_notifications: any
  awesome_notifications_core: ^0.9.3
  cached_network_image: ^3.4.0
  collection: 1.18.0
  crypto: ^3.0.3
  deepgram_speech_to_text: ^2.1.1
  device_calendar: ^4.3.2

  docx_template: ^0.4.0
  encrypt: ^5.0.3
  envied: ^0.5.4+1
  equatable: 2.0.5
  #  fonnx:
  #    git:
  #      url: https://github.com/Telosnex/fonnx.git 
  #      ref: main
  expandable_text: ^2.3.0
  file_picker: ^8.0.5
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.6
  flutter_bloc: ^8.1.6
  flutter_blue_plus: ^1.32.7
  flutter_foreground_task: ^6.5.0

  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.2+1
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  flutter_silero_vad:
    git:
      url: https://github.com/char5742/flutter_silero_vad.git
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_tilt: any
  flutter_timezone: ^2.0.0
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  gradient_borders: ^1.0.1
  groq: ^0.0.5
  growthbook_sdk_flutter: ^3.9.2
  http: ^1.2.1
  instabug_flutter: ^13.0.0
  instabug_http_client: ^2.4.0
  internet_connection_checker_plus: ^2.5.0
  intl: ^0.19.0
  location: ^7.0.0
  lottie: ^3.1.2
  map_launcher: ^3.3.1
  mime: ^1.0.5
  mime_type: 1.0.0

  #  flutter_foreground_task: ^6.2.0
  mixpanel_flutter: ^2.2.0
  ml_linalg: any
  objectbox: ^4.0.1
  objectbox_flutter_libs: any
  onesignal_flutter: ^5.2.5
  opus_dart: ^3.0.1
  opus_flutter: ^3.0.2
  #  nordic_dfu: ^6.1.4+hotfix
  package_info_plus: ^8.0.0
  page_transition: 2.1.0
  path: ^1.9.0

  path_provider: any
  pdf: ^3.11.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  record: ^5.1.2
  restart_app: ^1.2.1
  share_plus: ^9.0.0

  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sign_in_button: ^3.2.0
  sign_in_with_apple: ^6.1.1
  smooth_page_indicator: 1.1.0
  swipe: ^0.0.1
  top_snackbar_flutter: ^3.1.0
  tuple: ^2.0.2
  tutorial_coach_mark: ^1.2.11
  upgrader: ^10.3.0
  url_launcher: ^6.3.1
  url_launcher_platform_interface: 2.3.2
  uuid: ^4.4.0
  wav: ^1.3.0
  web_socket_channel: ^2.1.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000


dependency_overrides:
  http: ^1.2.1
  uuid: ^4.4.0
  opus_flutter_ios:
    git:
      url: https://github.com/mdmohsin7/opus_flutter.git
      path: opus_flutter_ios
      ref: dev
  opus_flutter_android:
    git:
      url: https://github.com/mdmohsin7/opus_flutter.git
      path: opus_flutter_android
  web: ^1.0.0
dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  flutter_flavorizr: ^2.2.3
  flutter_launcher_icons: 0.13.1
  flutter_lints: ^4.0.0
  lorem_ipsum: ^0.0.3
  flutter_test:
    sdk: flutter
  image: ^4.2.0
  integration_test:
    sdk: flutter
  lints: ^4.0.0
  objectbox_generator: any

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  # web:
  #   generate: false
  image_path: "assets/images/app_launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
  - assets/images/blob.png
  - assets/images/stars.png
  - assets/images/herologo.png
  - assets/images/backbutton.svg
  - assets/fonts/
  - assets/documents/
  - assets/images/
  - assets/videos/
  - assets/audios/
  - assets/lottie_animations/
  - assets/rive_animations/
  - assets/pdfs/
  - assets/silero_vad.onnx
  fonts:
  - family: "SF Pro Display"
    fonts:
    - asset: assets/fonts/SFPRODISPLAYTHINITALIC.OTF
      weight: 100
      style: italic
    - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
      weight: 300
      style: italic
    - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
    - asset: assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF
      style: italic
    - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
      weight: 500
    - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
      weight: 600
      style: italic
    - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
      weight: 700
    - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
      weight: 900
      style: italic

flutter_native_splash:


  background_image: "assets/images/splash.png"
  image: assets/images/logo.png
  android_12:

    background_image: "assets/images/splash.png"
    image: assets/images/logo.png

  android: true
  ios: true
